package app.creditapp.inf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RulesService", targetNamespace = "http://webservice.dhcc.com/")
public interface RulesService {

	/**
	 * 
	 * @param req
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "resp", targetNamespace = "")
	@RequestWrapper(localName = "queryResult", targetNamespace = "http://webservice.dhcc.com/", className = "app.creditapp.inf.client.QueryResult")
	@ResponseWrapper(localName = "queryResultResponse", targetNamespace = "http://webservice.dhcc.com/", className = "app.creditapp.inf.entity.QueryResultResponse")
	public String queryResult(
			@WebParam(name = "req", targetNamespace = "") String req);

	/**
	 * 
	 * @param req
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "resp", targetNamespace = "")
	@RequestWrapper(localName = "executeRule", targetNamespace = "http://webservice.dhcc.com/", className = "app.creditapp.inf.client.ExecuteRule")
	@ResponseWrapper(localName = "executeRuleResponse", targetNamespace = "http://webservice.dhcc.com/", className = "app.creditapp.inf.entity.ExecuteRuleResponse")
	public String executeRule(
			@WebParam(name = "req", targetNamespace = "") String req);

}
